# Following the steps to finish exercise 1

1. Import the numpy library as np:

In [4]:
# your code
import numpy as np

2. Create a two-dimensional array called A for storing the [[1,3,5],[2,4,6],[7,8,9]] matrix using np.mat:

In [5]:
# Your code
A = np.array ([[1,3,5],[2,4,6],[7,8,9]])

matrix([[1, 3, 5],
        [2, 4, 6],
        [7, 8, 9]])

3. Perform matrix multiplication using the asterisk and save the result in a variable called matmult:

In [6]:
# Your code
A * A

matrix([[ 42,  55,  68],
        [ 52,  70,  88],
        [ 86, 125, 164]])

4. Use np.matrix.transpose to get the transpose of the matrix and save the result in a variable called transpose:

In [7]:
# Your code
np.matrix.traspose(A)

matrix([[1, 2, 7],
        [3, 4, 8],
        [5, 6, 9]])